# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: vagrant

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    # Runs a single command using the runners shell
    - name: Build and push docker file
      run: |
        docker build . -t ghcr.io/esoterics/vagranthehe/vagrant:1.0.0
        docker image push ghcr.io/esoterics/vagranthehe/vagrant:1.0.0
